### ISSUE TITLE
"unreachable blob" is now "dangling blob"

### ISSUE THREAD

**Issue by clickonben** [ethomson/git-recover#10]
In the below line it is looking lines that start with "unreachable blob" however the git command now outputs "dangling blob [id]" on each line so the script as-is never finds anything.

BLOBS=($(git fsck --unreachable --no-reflogs \  
"${FULLNESS}" --no-progress | sed -ne 's/^unreachable blob //p'))

If you change it to the below it works.

BLOBS=($(git fsck --unreachable --no-reflogs \  
"${FULLNESS}" --no-progress | sed -ne 's/^dangling blob //p'))

**Comment by ethomson** [comment]
Fixed via #11 - thanks for letting me know!
