### ISSUE TITLE
--help text

### ISSUE THREAD

**Issue by giodamelio** [ethomson/git-recover#4]
When I run `git recover --help` it tells me there is no man page for the script. When I run `git recover -h` it prints a very minimal usage.

Would you me be open to me contributing a pull that expands a bit on the help text, and uses [`help2man`](https://www.gnu.org/software/help2man/) to generate a man page?

**Comment by ethomson** [comment]
I added `--help` in #11. Sorry about the delay in seeing this. 😓 Certainly I'd be open to a PR for a manpage by anyone who is interested, but I'll close this in the meantime.
